### ISSUE TITLE
Refinery still broken / console error

### ISSUE THREAD

**Issue by Gosts** [Rivinator/NoXRP2-Issues#4]
After a period of time on the server the refinery ceased working, ore goes into negative refining time. It seems to break for everyone at once on the server. As soon as one person notices it isn't working it's broken for everyone. Not sure what triggers it.

I found this error in my console at around the same time, although I don't know if they're related or not.

[ERROR] lua/noxiousnet/extensions/sh_string.lua:37: bad argument #1 to 'find' (string expected, got nil)
1. find - [C]:-1
   1. Replace - lua/noxiousnet/extensions/sh_string.lua:37
   2. unknown - gamemodes/noxrp/gamemode/vgui/dcraftingmenu.lua:67

**Comment by Rivinator** [comment]
Should be truly fixed now.
